name: Summarizer

on:
  workflow_dispatch:
  schedule:
    - cron: "0 20 * * *"
    # To run the script every day at 5:00 a.m. in Japan time, you would need to schedule the job to run at 8:00 p.m. UTC the previous day (because Japan is 9 hours ahead of UTC). This can be done in the workflow file by setting the `cron` parameter in the `schedule` event.

jobs:
  summarize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run summarizer.py
        run: python summarizer.py
        env:
          OPEN_AI_TOKEN: ${{ secrets.OPEN_AI_TOKEN }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_POST_CHANNEL_ID: ${{ secrets.SLACK_POST_CHANNEL_ID }}
          LANGUAGE: ${{ vars.LANGUAGE }}
          TIMEZONE: ${{ vars.TIMEZONE }}
          TEMPERATURE: ${{ vars.TEMPERATURE }}
          CHAT_MODEL: ${{ vars.CHAT_MODEL }}
          ENCODING_MODEL: ${{ vars.ENCODING_MODEL }}
          DEBUG: ${{ vars.DEBUG }}
          MAX_BODY_TOKENS: ${{ vars.MAX_BODY_TOKENS }}
          REQUEST_INTERVAL: ${{ vars.REQUEST_INTERVAL }}